// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MethodMark.proto

package com.daysh.apiface.serializer;

public final class MethodMarkSerializer {
  private MethodMarkSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MethodMarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MethodMark)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    String getDesc();
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    java.util.List<GeneralTagSerializer.GeneralTag>
        getDocTagsList();
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    GeneralTagSerializer.GeneralTag getDocTags(int index);
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    int getDocTagsCount();
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder>
        getDocTagsOrBuilderList();
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
            int index);

    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    java.util.List<ParamMarkSerializer.ParamMark>
        getParamsList();
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    ParamMarkSerializer.ParamMark getParams(int index);
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    java.util.List<? extends ParamMarkSerializer.ParamMarkOrBuilder>
        getParamsOrBuilderList();
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    ParamMarkSerializer.ParamMarkOrBuilder getParamsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code MethodMark}
   */
  public static final class MethodMark extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MethodMark)
      MethodMarkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MethodMark.newBuilder() to construct.
    private MethodMark(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MethodMark() {
      name_ = "";
      desc_ = "";
      docTags_ = java.util.Collections.emptyList();
      params_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MethodMark();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MethodMark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                docTags_ = new java.util.ArrayList<GeneralTagSerializer.GeneralTag>();
                mutable_bitField0_ |= 0x00000001;
              }
              docTags_.add(
                  input.readMessage(GeneralTagSerializer.GeneralTag.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                params_ = new java.util.ArrayList<ParamMarkSerializer.ParamMark>();
                mutable_bitField0_ |= 0x00000002;
              }
              params_.add(
                  input.readMessage(ParamMarkSerializer.ParamMark.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          docTags_ = java.util.Collections.unmodifiableList(docTags_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MethodMarkSerializer.internal_static_MethodMark_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MethodMarkSerializer.internal_static_MethodMark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MethodMark.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile Object desc_;
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @Override
    public String getDesc() {
      Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCTAGS_FIELD_NUMBER = 3;
    private java.util.List<GeneralTagSerializer.GeneralTag> docTags_;
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public java.util.List<GeneralTagSerializer.GeneralTag> getDocTagsList() {
      return docTags_;
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder>
        getDocTagsOrBuilderList() {
      return docTags_;
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public int getDocTagsCount() {
      return docTags_.size();
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public GeneralTagSerializer.GeneralTag getDocTags(int index) {
      return docTags_.get(index);
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
        int index) {
      return docTags_.get(index);
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private java.util.List<ParamMarkSerializer.ParamMark> params_;
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    @Override
    public java.util.List<ParamMarkSerializer.ParamMark> getParamsList() {
      return params_;
    }
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    @Override
    public java.util.List<? extends ParamMarkSerializer.ParamMarkOrBuilder>
        getParamsOrBuilderList() {
      return params_;
    }
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    @Override
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    @Override
    public ParamMarkSerializer.ParamMark getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated .ParamMark params = 4;</code>
     */
    @Override
    public ParamMarkSerializer.ParamMarkOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      for (int i = 0; i < docTags_.size(); i++) {
        output.writeMessage(3, docTags_.get(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(4, params_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      for (int i = 0; i < docTags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, docTags_.get(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, params_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MethodMark)) {
        return super.equals(obj);
      }
      MethodMark other = (MethodMark) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (!getDocTagsList()
          .equals(other.getDocTagsList())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      if (getDocTagsCount() > 0) {
        hash = (37 * hash) + DOCTAGS_FIELD_NUMBER;
        hash = (53 * hash) + getDocTagsList().hashCode();
      }
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MethodMark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MethodMark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MethodMark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MethodMark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MethodMark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MethodMark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MethodMark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MethodMark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MethodMark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MethodMark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MethodMark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MethodMark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MethodMark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MethodMark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MethodMark)
        MethodMarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MethodMarkSerializer.internal_static_MethodMark_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MethodMarkSerializer.internal_static_MethodMark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MethodMark.class, Builder.class);
      }

      // Construct using MethodMarkSerializer.MethodMark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDocTagsFieldBuilder();
          getParamsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        desc_ = "";

        if (docTagsBuilder_ == null) {
          docTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          docTagsBuilder_.clear();
        }
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MethodMarkSerializer.internal_static_MethodMark_descriptor;
      }

      @Override
      public MethodMark getDefaultInstanceForType() {
        return MethodMark.getDefaultInstance();
      }

      @Override
      public MethodMark build() {
        MethodMark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MethodMark buildPartial() {
        MethodMark result = new MethodMark(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.desc_ = desc_;
        if (docTagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            docTags_ = java.util.Collections.unmodifiableList(docTags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.docTags_ = docTags_;
        } else {
          result.docTags_ = docTagsBuilder_.build();
        }
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MethodMark) {
          return mergeFrom((MethodMark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MethodMark other) {
        if (other == MethodMark.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (docTagsBuilder_ == null) {
          if (!other.docTags_.isEmpty()) {
            if (docTags_.isEmpty()) {
              docTags_ = other.docTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocTagsIsMutable();
              docTags_.addAll(other.docTags_);
            }
            onChanged();
          }
        } else {
          if (!other.docTags_.isEmpty()) {
            if (docTagsBuilder_.isEmpty()) {
              docTagsBuilder_.dispose();
              docTagsBuilder_ = null;
              docTags_ = other.docTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              docTagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDocTagsFieldBuilder() : null;
            } else {
              docTagsBuilder_.addAllMessages(other.docTags_);
            }
          }
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000002);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MethodMark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MethodMark) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object desc_ = "";
      /**
       * <code>string desc = 2;</code>
       * @return The desc.
       */
      public String getDesc() {
        Object ref = desc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private java.util.List<GeneralTagSerializer.GeneralTag> docTags_ =
        java.util.Collections.emptyList();
      private void ensureDocTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          docTags_ = new java.util.ArrayList<GeneralTagSerializer.GeneralTag>(docTags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder> docTagsBuilder_;

      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public java.util.List<GeneralTagSerializer.GeneralTag> getDocTagsList() {
        if (docTagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(docTags_);
        } else {
          return docTagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public int getDocTagsCount() {
        if (docTagsBuilder_ == null) {
          return docTags_.size();
        } else {
          return docTagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag getDocTags(int index) {
        if (docTagsBuilder_ == null) {
          return docTags_.get(index);
        } else {
          return docTagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder setDocTags(
          int index, GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.set(index, value);
          onChanged();
        } else {
          docTagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder setDocTags(
          int index, GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.set(index, builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.add(value);
          onChanged();
        } else {
          docTagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(
          int index, GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.add(index, value);
          onChanged();
        } else {
          docTagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(
          GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.add(builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(
          int index, GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.add(index, builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addAllDocTags(
          Iterable<? extends GeneralTagSerializer.GeneralTag> values) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, docTags_);
          onChanged();
        } else {
          docTagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder clearDocTags() {
        if (docTagsBuilder_ == null) {
          docTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          docTagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder removeDocTags(int index) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.remove(index);
          onChanged();
        } else {
          docTagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder getDocTagsBuilder(
          int index) {
        return getDocTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
          int index) {
        if (docTagsBuilder_ == null) {
          return docTags_.get(index);  } else {
          return docTagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder>
           getDocTagsOrBuilderList() {
        if (docTagsBuilder_ != null) {
          return docTagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(docTags_);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder addDocTagsBuilder() {
        return getDocTagsFieldBuilder().addBuilder(
            GeneralTagSerializer.GeneralTag.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder addDocTagsBuilder(
          int index) {
        return getDocTagsFieldBuilder().addBuilder(
            index, GeneralTagSerializer.GeneralTag.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public java.util.List<GeneralTagSerializer.GeneralTag.Builder>
           getDocTagsBuilderList() {
        return getDocTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder>
          getDocTagsFieldBuilder() {
        if (docTagsBuilder_ == null) {
          docTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder>(
                  docTags_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          docTags_ = null;
        }
        return docTagsBuilder_;
      }

      private java.util.List<ParamMarkSerializer.ParamMark> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          params_ = new java.util.ArrayList<ParamMarkSerializer.ParamMark>(params_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ParamMarkSerializer.ParamMark, ParamMarkSerializer.ParamMark.Builder, ParamMarkSerializer.ParamMarkOrBuilder> paramsBuilder_;

      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public java.util.List<ParamMarkSerializer.ParamMark> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public ParamMarkSerializer.ParamMark getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder setParams(
          int index, ParamMarkSerializer.ParamMark value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder setParams(
          int index, ParamMarkSerializer.ParamMark.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder addParams(ParamMarkSerializer.ParamMark value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder addParams(
          int index, ParamMarkSerializer.ParamMark value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder addParams(
          ParamMarkSerializer.ParamMark.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder addParams(
          int index, ParamMarkSerializer.ParamMark.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder addAllParams(
          Iterable<? extends ParamMarkSerializer.ParamMark> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public ParamMarkSerializer.ParamMark.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public ParamMarkSerializer.ParamMarkOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public java.util.List<? extends ParamMarkSerializer.ParamMarkOrBuilder>
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public ParamMarkSerializer.ParamMark.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            ParamMarkSerializer.ParamMark.getDefaultInstance());
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public ParamMarkSerializer.ParamMark.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, ParamMarkSerializer.ParamMark.getDefaultInstance());
      }
      /**
       * <code>repeated .ParamMark params = 4;</code>
       */
      public java.util.List<ParamMarkSerializer.ParamMark.Builder>
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ParamMarkSerializer.ParamMark, ParamMarkSerializer.ParamMark.Builder, ParamMarkSerializer.ParamMarkOrBuilder>
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ParamMarkSerializer.ParamMark, ParamMarkSerializer.ParamMark.Builder, ParamMarkSerializer.ParamMarkOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MethodMark)
    }

    // @@protoc_insertion_point(class_scope:MethodMark)
    private static final MethodMark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MethodMark();
    }

    public static MethodMark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MethodMark>
        PARSER = new com.google.protobuf.AbstractParser<MethodMark>() {
      @Override
      public MethodMark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MethodMark(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MethodMark> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MethodMark> getParserForType() {
      return PARSER;
    }

    @Override
    public MethodMark getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MethodMark_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MethodMark_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020MethodMark.proto\032\017ParamMark.proto\032\020Gen" +
      "eralTag.proto\"b\n\nMethodMark\022\014\n\004name\030\001 \001(" +
      "\t\022\014\n\004desc\030\002 \001(\t\022\034\n\007docTags\030\003 \003(\0132\013.Gener" +
      "alTag\022\032\n\006params\030\004 \003(\0132\n.ParamMarkB4\n\034com" +
      ".daysh.apiface.serializerB\024MethodMarkSer" +
      "ializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ParamMarkSerializer.getDescriptor(),
          GeneralTagSerializer.getDescriptor(),
        });
    internal_static_MethodMark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MethodMark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MethodMark_descriptor,
        new String[] { "Name", "Desc", "DocTags", "Params", });
    ParamMarkSerializer.getDescriptor();
    GeneralTagSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
