// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClassMark.proto

package io.github.dayeshing.apiface.serializer;

public final class ClassMarkSerializer {
  private ClassMarkSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClassMarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClassMark)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    String getDesc();
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    java.util.List<GeneralTagSerializer.GeneralTag> 
        getDocTagsList();
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    GeneralTagSerializer.GeneralTag getDocTags(int index);
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    int getDocTagsCount();
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder> 
        getDocTagsOrBuilderList();
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
            int index);

    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    java.util.List<FieldMarkSerializer.FieldMark> 
        getFieldsList();
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    FieldMarkSerializer.FieldMark getFields(int index);
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    java.util.List<? extends FieldMarkSerializer.FieldMarkOrBuilder> 
        getFieldsOrBuilderList();
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    FieldMarkSerializer.FieldMarkOrBuilder getFieldsOrBuilder(
            int index);

    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    java.util.List<MethodMarkSerializer.MethodMark> 
        getMethodsList();
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    MethodMarkSerializer.MethodMark getMethods(int index);
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    int getMethodsCount();
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    java.util.List<? extends MethodMarkSerializer.MethodMarkOrBuilder> 
        getMethodsOrBuilderList();
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    MethodMarkSerializer.MethodMarkOrBuilder getMethodsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code ClassMark}
   */
  public static final class ClassMark extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClassMark)
      ClassMarkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClassMark.newBuilder() to construct.
    private ClassMark(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClassMark() {
      name_ = "";
      desc_ = "";
      docTags_ = java.util.Collections.emptyList();
      fields_ = java.util.Collections.emptyList();
      methods_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClassMark();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClassMark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                docTags_ = new java.util.ArrayList<GeneralTagSerializer.GeneralTag>();
                mutable_bitField0_ |= 0x00000001;
              }
              docTags_.add(
                  input.readMessage(GeneralTagSerializer.GeneralTag.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                fields_ = new java.util.ArrayList<FieldMarkSerializer.FieldMark>();
                mutable_bitField0_ |= 0x00000002;
              }
              fields_.add(
                  input.readMessage(FieldMarkSerializer.FieldMark.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                methods_ = new java.util.ArrayList<MethodMarkSerializer.MethodMark>();
                mutable_bitField0_ |= 0x00000004;
              }
              methods_.add(
                  input.readMessage(MethodMarkSerializer.MethodMark.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          docTags_ = java.util.Collections.unmodifiableList(docTags_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClassMarkSerializer.internal_static_ClassMark_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClassMarkSerializer.internal_static_ClassMark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClassMark.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile Object desc_;
    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @Override
    public String getDesc() {
      Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCTAGS_FIELD_NUMBER = 3;
    private java.util.List<GeneralTagSerializer.GeneralTag> docTags_;
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public java.util.List<GeneralTagSerializer.GeneralTag> getDocTagsList() {
      return docTags_;
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder> 
        getDocTagsOrBuilderList() {
      return docTags_;
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public int getDocTagsCount() {
      return docTags_.size();
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public GeneralTagSerializer.GeneralTag getDocTags(int index) {
      return docTags_.get(index);
    }
    /**
     * <code>repeated .GeneralTag docTags = 3;</code>
     */
    @Override
    public GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
        int index) {
      return docTags_.get(index);
    }

    public static final int FIELDS_FIELD_NUMBER = 4;
    private java.util.List<FieldMarkSerializer.FieldMark> fields_;
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    @Override
    public java.util.List<FieldMarkSerializer.FieldMark> getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    @Override
    public java.util.List<? extends FieldMarkSerializer.FieldMarkOrBuilder> 
        getFieldsOrBuilderList() {
      return fields_;
    }
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    @Override
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    @Override
    public FieldMarkSerializer.FieldMark getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated .FieldMark fields = 4;</code>
     */
    @Override
    public FieldMarkSerializer.FieldMarkOrBuilder getFieldsOrBuilder(
        int index) {
      return fields_.get(index);
    }

    public static final int METHODS_FIELD_NUMBER = 5;
    private java.util.List<MethodMarkSerializer.MethodMark> methods_;
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    @Override
    public java.util.List<MethodMarkSerializer.MethodMark> getMethodsList() {
      return methods_;
    }
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    @Override
    public java.util.List<? extends MethodMarkSerializer.MethodMarkOrBuilder> 
        getMethodsOrBuilderList() {
      return methods_;
    }
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    @Override
    public int getMethodsCount() {
      return methods_.size();
    }
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    @Override
    public MethodMarkSerializer.MethodMark getMethods(int index) {
      return methods_.get(index);
    }
    /**
     * <code>repeated .MethodMark methods = 5;</code>
     */
    @Override
    public MethodMarkSerializer.MethodMarkOrBuilder getMethodsOrBuilder(
        int index) {
      return methods_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      for (int i = 0; i < docTags_.size(); i++) {
        output.writeMessage(3, docTags_.get(i));
      }
      for (int i = 0; i < fields_.size(); i++) {
        output.writeMessage(4, fields_.get(i));
      }
      for (int i = 0; i < methods_.size(); i++) {
        output.writeMessage(5, methods_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      for (int i = 0; i < docTags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, docTags_.get(i));
      }
      for (int i = 0; i < fields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, fields_.get(i));
      }
      for (int i = 0; i < methods_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, methods_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClassMark)) {
        return super.equals(obj);
      }
      ClassMark other = (ClassMark) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (!getDocTagsList()
          .equals(other.getDocTagsList())) return false;
      if (!getFieldsList()
          .equals(other.getFieldsList())) return false;
      if (!getMethodsList()
          .equals(other.getMethodsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      if (getDocTagsCount() > 0) {
        hash = (37 * hash) + DOCTAGS_FIELD_NUMBER;
        hash = (53 * hash) + getDocTagsList().hashCode();
      }
      if (getFieldsCount() > 0) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldsList().hashCode();
      }
      if (getMethodsCount() > 0) {
        hash = (37 * hash) + METHODS_FIELD_NUMBER;
        hash = (53 * hash) + getMethodsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClassMark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClassMark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClassMark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClassMark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClassMark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClassMark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClassMark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClassMark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClassMark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClassMark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClassMark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClassMark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClassMark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClassMark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClassMark)
        ClassMarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClassMarkSerializer.internal_static_ClassMark_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClassMarkSerializer.internal_static_ClassMark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClassMark.class, Builder.class);
      }

      // Construct using ClassMarkSerializer.ClassMark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDocTagsFieldBuilder();
          getFieldsFieldBuilder();
          getMethodsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        desc_ = "";

        if (docTagsBuilder_ == null) {
          docTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          docTagsBuilder_.clear();
        }
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          fieldsBuilder_.clear();
        }
        if (methodsBuilder_ == null) {
          methods_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          methodsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClassMarkSerializer.internal_static_ClassMark_descriptor;
      }

      @Override
      public ClassMark getDefaultInstanceForType() {
        return ClassMark.getDefaultInstance();
      }

      @Override
      public ClassMark build() {
        ClassMark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClassMark buildPartial() {
        ClassMark result = new ClassMark(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.desc_ = desc_;
        if (docTagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            docTags_ = java.util.Collections.unmodifiableList(docTags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.docTags_ = docTags_;
        } else {
          result.docTags_ = docTagsBuilder_.build();
        }
        if (fieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            fields_ = java.util.Collections.unmodifiableList(fields_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.fields_ = fields_;
        } else {
          result.fields_ = fieldsBuilder_.build();
        }
        if (methodsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            methods_ = java.util.Collections.unmodifiableList(methods_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.methods_ = methods_;
        } else {
          result.methods_ = methodsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClassMark) {
          return mergeFrom((ClassMark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClassMark other) {
        if (other == ClassMark.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (docTagsBuilder_ == null) {
          if (!other.docTags_.isEmpty()) {
            if (docTags_.isEmpty()) {
              docTags_ = other.docTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocTagsIsMutable();
              docTags_.addAll(other.docTags_);
            }
            onChanged();
          }
        } else {
          if (!other.docTags_.isEmpty()) {
            if (docTagsBuilder_.isEmpty()) {
              docTagsBuilder_.dispose();
              docTagsBuilder_ = null;
              docTags_ = other.docTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              docTagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDocTagsFieldBuilder() : null;
            } else {
              docTagsBuilder_.addAllMessages(other.docTags_);
            }
          }
        }
        if (fieldsBuilder_ == null) {
          if (!other.fields_.isEmpty()) {
            if (fields_.isEmpty()) {
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFieldsIsMutable();
              fields_.addAll(other.fields_);
            }
            onChanged();
          }
        } else {
          if (!other.fields_.isEmpty()) {
            if (fieldsBuilder_.isEmpty()) {
              fieldsBuilder_.dispose();
              fieldsBuilder_ = null;
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000002);
              fieldsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFieldsFieldBuilder() : null;
            } else {
              fieldsBuilder_.addAllMessages(other.fields_);
            }
          }
        }
        if (methodsBuilder_ == null) {
          if (!other.methods_.isEmpty()) {
            if (methods_.isEmpty()) {
              methods_ = other.methods_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMethodsIsMutable();
              methods_.addAll(other.methods_);
            }
            onChanged();
          }
        } else {
          if (!other.methods_.isEmpty()) {
            if (methodsBuilder_.isEmpty()) {
              methodsBuilder_.dispose();
              methodsBuilder_ = null;
              methods_ = other.methods_;
              bitField0_ = (bitField0_ & ~0x00000004);
              methodsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMethodsFieldBuilder() : null;
            } else {
              methodsBuilder_.addAllMessages(other.methods_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClassMark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClassMark) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object desc_ = "";
      /**
       * <code>string desc = 2;</code>
       * @return The desc.
       */
      public String getDesc() {
        Object ref = desc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private java.util.List<GeneralTagSerializer.GeneralTag> docTags_ =
        java.util.Collections.emptyList();
      private void ensureDocTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          docTags_ = new java.util.ArrayList<GeneralTagSerializer.GeneralTag>(docTags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder> docTagsBuilder_;

      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public java.util.List<GeneralTagSerializer.GeneralTag> getDocTagsList() {
        if (docTagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(docTags_);
        } else {
          return docTagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public int getDocTagsCount() {
        if (docTagsBuilder_ == null) {
          return docTags_.size();
        } else {
          return docTagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag getDocTags(int index) {
        if (docTagsBuilder_ == null) {
          return docTags_.get(index);
        } else {
          return docTagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder setDocTags(
          int index, GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.set(index, value);
          onChanged();
        } else {
          docTagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder setDocTags(
          int index, GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.set(index, builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.add(value);
          onChanged();
        } else {
          docTagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(
          int index, GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.add(index, value);
          onChanged();
        } else {
          docTagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(
          GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.add(builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addDocTags(
          int index, GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.add(index, builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder addAllDocTags(
          Iterable<? extends GeneralTagSerializer.GeneralTag> values) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, docTags_);
          onChanged();
        } else {
          docTagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder clearDocTags() {
        if (docTagsBuilder_ == null) {
          docTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          docTagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public Builder removeDocTags(int index) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.remove(index);
          onChanged();
        } else {
          docTagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder getDocTagsBuilder(
          int index) {
        return getDocTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
          int index) {
        if (docTagsBuilder_ == null) {
          return docTags_.get(index);  } else {
          return docTagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder> 
           getDocTagsOrBuilderList() {
        if (docTagsBuilder_ != null) {
          return docTagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(docTags_);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder addDocTagsBuilder() {
        return getDocTagsFieldBuilder().addBuilder(
            GeneralTagSerializer.GeneralTag.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder addDocTagsBuilder(
          int index) {
        return getDocTagsFieldBuilder().addBuilder(
            index, GeneralTagSerializer.GeneralTag.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralTag docTags = 3;</code>
       */
      public java.util.List<GeneralTagSerializer.GeneralTag.Builder> 
           getDocTagsBuilderList() {
        return getDocTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder> 
          getDocTagsFieldBuilder() {
        if (docTagsBuilder_ == null) {
          docTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder>(
                  docTags_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          docTags_ = null;
        }
        return docTagsBuilder_;
      }

      private java.util.List<FieldMarkSerializer.FieldMark> fields_ =
        java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          fields_ = new java.util.ArrayList<FieldMarkSerializer.FieldMark>(fields_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          FieldMarkSerializer.FieldMark, FieldMarkSerializer.FieldMark.Builder, FieldMarkSerializer.FieldMarkOrBuilder> fieldsBuilder_;

      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public java.util.List<FieldMarkSerializer.FieldMark> getFieldsList() {
        if (fieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fields_);
        } else {
          return fieldsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public int getFieldsCount() {
        if (fieldsBuilder_ == null) {
          return fields_.size();
        } else {
          return fieldsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public FieldMarkSerializer.FieldMark getFields(int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);
        } else {
          return fieldsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder setFields(
          int index, FieldMarkSerializer.FieldMark value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.set(index, value);
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder setFields(
          int index, FieldMarkSerializer.FieldMark.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder addFields(FieldMarkSerializer.FieldMark value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder addFields(
          int index, FieldMarkSerializer.FieldMark value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(index, value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder addFields(
          FieldMarkSerializer.FieldMark.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder addFields(
          int index, FieldMarkSerializer.FieldMark.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder addAllFields(
          Iterable<? extends FieldMarkSerializer.FieldMark> values) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fields_);
          onChanged();
        } else {
          fieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder clearFields() {
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public Builder removeFields(int index) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.remove(index);
          onChanged();
        } else {
          fieldsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public FieldMarkSerializer.FieldMark.Builder getFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public FieldMarkSerializer.FieldMarkOrBuilder getFieldsOrBuilder(
          int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);  } else {
          return fieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public java.util.List<? extends FieldMarkSerializer.FieldMarkOrBuilder> 
           getFieldsOrBuilderList() {
        if (fieldsBuilder_ != null) {
          return fieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fields_);
        }
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public FieldMarkSerializer.FieldMark.Builder addFieldsBuilder() {
        return getFieldsFieldBuilder().addBuilder(
            FieldMarkSerializer.FieldMark.getDefaultInstance());
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public FieldMarkSerializer.FieldMark.Builder addFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().addBuilder(
            index, FieldMarkSerializer.FieldMark.getDefaultInstance());
      }
      /**
       * <code>repeated .FieldMark fields = 4;</code>
       */
      public java.util.List<FieldMarkSerializer.FieldMark.Builder> 
           getFieldsBuilderList() {
        return getFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          FieldMarkSerializer.FieldMark, FieldMarkSerializer.FieldMark.Builder, FieldMarkSerializer.FieldMarkOrBuilder> 
          getFieldsFieldBuilder() {
        if (fieldsBuilder_ == null) {
          fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              FieldMarkSerializer.FieldMark, FieldMarkSerializer.FieldMark.Builder, FieldMarkSerializer.FieldMarkOrBuilder>(
                  fields_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          fields_ = null;
        }
        return fieldsBuilder_;
      }

      private java.util.List<MethodMarkSerializer.MethodMark> methods_ =
        java.util.Collections.emptyList();
      private void ensureMethodsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          methods_ = new java.util.ArrayList<MethodMarkSerializer.MethodMark>(methods_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MethodMarkSerializer.MethodMark, MethodMarkSerializer.MethodMark.Builder, MethodMarkSerializer.MethodMarkOrBuilder> methodsBuilder_;

      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public java.util.List<MethodMarkSerializer.MethodMark> getMethodsList() {
        if (methodsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(methods_);
        } else {
          return methodsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public int getMethodsCount() {
        if (methodsBuilder_ == null) {
          return methods_.size();
        } else {
          return methodsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public MethodMarkSerializer.MethodMark getMethods(int index) {
        if (methodsBuilder_ == null) {
          return methods_.get(index);
        } else {
          return methodsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder setMethods(
          int index, MethodMarkSerializer.MethodMark value) {
        if (methodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMethodsIsMutable();
          methods_.set(index, value);
          onChanged();
        } else {
          methodsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder setMethods(
          int index, MethodMarkSerializer.MethodMark.Builder builderForValue) {
        if (methodsBuilder_ == null) {
          ensureMethodsIsMutable();
          methods_.set(index, builderForValue.build());
          onChanged();
        } else {
          methodsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder addMethods(MethodMarkSerializer.MethodMark value) {
        if (methodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMethodsIsMutable();
          methods_.add(value);
          onChanged();
        } else {
          methodsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder addMethods(
          int index, MethodMarkSerializer.MethodMark value) {
        if (methodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMethodsIsMutable();
          methods_.add(index, value);
          onChanged();
        } else {
          methodsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder addMethods(
          MethodMarkSerializer.MethodMark.Builder builderForValue) {
        if (methodsBuilder_ == null) {
          ensureMethodsIsMutable();
          methods_.add(builderForValue.build());
          onChanged();
        } else {
          methodsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder addMethods(
          int index, MethodMarkSerializer.MethodMark.Builder builderForValue) {
        if (methodsBuilder_ == null) {
          ensureMethodsIsMutable();
          methods_.add(index, builderForValue.build());
          onChanged();
        } else {
          methodsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder addAllMethods(
          Iterable<? extends MethodMarkSerializer.MethodMark> values) {
        if (methodsBuilder_ == null) {
          ensureMethodsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, methods_);
          onChanged();
        } else {
          methodsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder clearMethods() {
        if (methodsBuilder_ == null) {
          methods_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          methodsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public Builder removeMethods(int index) {
        if (methodsBuilder_ == null) {
          ensureMethodsIsMutable();
          methods_.remove(index);
          onChanged();
        } else {
          methodsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public MethodMarkSerializer.MethodMark.Builder getMethodsBuilder(
          int index) {
        return getMethodsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public MethodMarkSerializer.MethodMarkOrBuilder getMethodsOrBuilder(
          int index) {
        if (methodsBuilder_ == null) {
          return methods_.get(index);  } else {
          return methodsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public java.util.List<? extends MethodMarkSerializer.MethodMarkOrBuilder> 
           getMethodsOrBuilderList() {
        if (methodsBuilder_ != null) {
          return methodsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(methods_);
        }
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public MethodMarkSerializer.MethodMark.Builder addMethodsBuilder() {
        return getMethodsFieldBuilder().addBuilder(
            MethodMarkSerializer.MethodMark.getDefaultInstance());
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public MethodMarkSerializer.MethodMark.Builder addMethodsBuilder(
          int index) {
        return getMethodsFieldBuilder().addBuilder(
            index, MethodMarkSerializer.MethodMark.getDefaultInstance());
      }
      /**
       * <code>repeated .MethodMark methods = 5;</code>
       */
      public java.util.List<MethodMarkSerializer.MethodMark.Builder> 
           getMethodsBuilderList() {
        return getMethodsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MethodMarkSerializer.MethodMark, MethodMarkSerializer.MethodMark.Builder, MethodMarkSerializer.MethodMarkOrBuilder> 
          getMethodsFieldBuilder() {
        if (methodsBuilder_ == null) {
          methodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MethodMarkSerializer.MethodMark, MethodMarkSerializer.MethodMark.Builder, MethodMarkSerializer.MethodMarkOrBuilder>(
                  methods_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          methods_ = null;
        }
        return methodsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClassMark)
    }

    // @@protoc_insertion_point(class_scope:ClassMark)
    private static final ClassMark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClassMark();
    }

    public static ClassMark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClassMark>
        PARSER = new com.google.protobuf.AbstractParser<ClassMark>() {
      @Override
      public ClassMark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClassMark(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClassMark> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClassMark> getParserForType() {
      return PARSER;
    }

    @Override
    public ClassMark getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClassMark_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClassMark_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017ClassMark.proto\032\017FieldMark.proto\032\020Gene" +
      "ralTag.proto\032\020MethodMark.proto\"\177\n\tClassM" +
      "ark\022\014\n\004name\030\001 \001(\t\022\014\n\004desc\030\002 \001(\t\022\034\n\007docTa" +
      "gs\030\003 \003(\0132\013.GeneralTag\022\032\n\006fields\030\004 \003(\0132\n." +
      "FieldMark\022\034\n\007methods\030\005 \003(\0132\013.MethodMarkB" +
      "3\n\034io.github.dayeshing.apiface.serializerB\023ClassMa" +
      "rkSerializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          FieldMarkSerializer.getDescriptor(),
          GeneralTagSerializer.getDescriptor(),
          MethodMarkSerializer.getDescriptor(),
        });
    internal_static_ClassMark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClassMark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClassMark_descriptor,
        new String[] { "Name", "Desc", "DocTags", "Fields", "Methods", });
    FieldMarkSerializer.getDescriptor();
    GeneralTagSerializer.getDescriptor();
    MethodMarkSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
