// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FieldMark.proto

package io.github.dayeshing.apiface.serializer;

public final class FieldMarkSerializer {
  private FieldMarkSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FieldMarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FieldMark)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string desc = 3;</code>
     * @return The desc.
     */
    String getDesc();
    /**
     * <code>string desc = 3;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>string example = 4;</code>
     * @return The example.
     */
    String getExample();
    /**
     * <code>string example = 4;</code>
     * @return The bytes for example.
     */
    com.google.protobuf.ByteString
        getExampleBytes();

    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    java.util.List<GeneralTagSerializer.GeneralTag> 
        getDocTagsList();
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    GeneralTagSerializer.GeneralTag getDocTags(int index);
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    int getDocTagsCount();
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder> 
        getDocTagsOrBuilderList();
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code FieldMark}
   */
  public static final class FieldMark extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FieldMark)
      FieldMarkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FieldMark.newBuilder() to construct.
    private FieldMark(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FieldMark() {
      type_ = "";
      name_ = "";
      desc_ = "";
      example_ = "";
      docTags_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new FieldMark();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FieldMark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              example_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                docTags_ = new java.util.ArrayList<GeneralTagSerializer.GeneralTag>();
                mutable_bitField0_ |= 0x00000001;
              }
              docTags_.add(
                  input.readMessage(GeneralTagSerializer.GeneralTag.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          docTags_ = java.util.Collections.unmodifiableList(docTags_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FieldMarkSerializer.internal_static_FieldMark_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FieldMarkSerializer.internal_static_FieldMark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FieldMark.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @Override
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 3;
    private volatile Object desc_;
    /**
     * <code>string desc = 3;</code>
     * @return The desc.
     */
    @Override
    public String getDesc() {
      Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 3;</code>
     * @return The bytes for desc.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXAMPLE_FIELD_NUMBER = 4;
    private volatile Object example_;
    /**
     * <code>string example = 4;</code>
     * @return The example.
     */
    @Override
    public String getExample() {
      Object ref = example_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        example_ = s;
        return s;
      }
    }
    /**
     * <code>string example = 4;</code>
     * @return The bytes for example.
     */
    @Override
    public com.google.protobuf.ByteString
        getExampleBytes() {
      Object ref = example_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        example_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCTAGS_FIELD_NUMBER = 5;
    private java.util.List<GeneralTagSerializer.GeneralTag> docTags_;
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    @Override
    public java.util.List<GeneralTagSerializer.GeneralTag> getDocTagsList() {
      return docTags_;
    }
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    @Override
    public java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder> 
        getDocTagsOrBuilderList() {
      return docTags_;
    }
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    @Override
    public int getDocTagsCount() {
      return docTags_.size();
    }
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    @Override
    public GeneralTagSerializer.GeneralTag getDocTags(int index) {
      return docTags_.get(index);
    }
    /**
     * <code>repeated .GeneralTag docTags = 5;</code>
     */
    @Override
    public GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
        int index) {
      return docTags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, desc_);
      }
      if (!getExampleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, example_);
      }
      for (int i = 0; i < docTags_.size(); i++) {
        output.writeMessage(5, docTags_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, desc_);
      }
      if (!getExampleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, example_);
      }
      for (int i = 0; i < docTags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, docTags_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FieldMark)) {
        return super.equals(obj);
      }
      FieldMark other = (FieldMark) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (!getExample()
          .equals(other.getExample())) return false;
      if (!getDocTagsList()
          .equals(other.getDocTagsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + EXAMPLE_FIELD_NUMBER;
      hash = (53 * hash) + getExample().hashCode();
      if (getDocTagsCount() > 0) {
        hash = (37 * hash) + DOCTAGS_FIELD_NUMBER;
        hash = (53 * hash) + getDocTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FieldMark parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FieldMark parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FieldMark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FieldMark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FieldMark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FieldMark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FieldMark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FieldMark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FieldMark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FieldMark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FieldMark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FieldMark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FieldMark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FieldMark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FieldMark)
        FieldMarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FieldMarkSerializer.internal_static_FieldMark_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FieldMarkSerializer.internal_static_FieldMark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FieldMark.class, Builder.class);
      }

      // Construct using FieldMarkSerializer.FieldMark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDocTagsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = "";

        name_ = "";

        desc_ = "";

        example_ = "";

        if (docTagsBuilder_ == null) {
          docTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          docTagsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FieldMarkSerializer.internal_static_FieldMark_descriptor;
      }

      @Override
      public FieldMark getDefaultInstanceForType() {
        return FieldMark.getDefaultInstance();
      }

      @Override
      public FieldMark build() {
        FieldMark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FieldMark buildPartial() {
        FieldMark result = new FieldMark(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.name_ = name_;
        result.desc_ = desc_;
        result.example_ = example_;
        if (docTagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            docTags_ = java.util.Collections.unmodifiableList(docTags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.docTags_ = docTags_;
        } else {
          result.docTags_ = docTagsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FieldMark) {
          return mergeFrom((FieldMark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FieldMark other) {
        if (other == FieldMark.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.getExample().isEmpty()) {
          example_ = other.example_;
          onChanged();
        }
        if (docTagsBuilder_ == null) {
          if (!other.docTags_.isEmpty()) {
            if (docTags_.isEmpty()) {
              docTags_ = other.docTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocTagsIsMutable();
              docTags_.addAll(other.docTags_);
            }
            onChanged();
          }
        } else {
          if (!other.docTags_.isEmpty()) {
            if (docTagsBuilder_.isEmpty()) {
              docTagsBuilder_.dispose();
              docTagsBuilder_ = null;
              docTags_ = other.docTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              docTagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDocTagsFieldBuilder() : null;
            } else {
              docTagsBuilder_.addAllMessages(other.docTags_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FieldMark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FieldMark) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object desc_ = "";
      /**
       * <code>string desc = 3;</code>
       * @return The desc.
       */
      public String getDesc() {
        Object ref = desc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string desc = 3;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 3;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 3;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private Object example_ = "";
      /**
       * <code>string example = 4;</code>
       * @return The example.
       */
      public String getExample() {
        Object ref = example_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          example_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string example = 4;</code>
       * @return The bytes for example.
       */
      public com.google.protobuf.ByteString
          getExampleBytes() {
        Object ref = example_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          example_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string example = 4;</code>
       * @param value The example to set.
       * @return This builder for chaining.
       */
      public Builder setExample(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        example_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string example = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExample() {
        
        example_ = getDefaultInstance().getExample();
        onChanged();
        return this;
      }
      /**
       * <code>string example = 4;</code>
       * @param value The bytes for example to set.
       * @return This builder for chaining.
       */
      public Builder setExampleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        example_ = value;
        onChanged();
        return this;
      }

      private java.util.List<GeneralTagSerializer.GeneralTag> docTags_ =
        java.util.Collections.emptyList();
      private void ensureDocTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          docTags_ = new java.util.ArrayList<GeneralTagSerializer.GeneralTag>(docTags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder> docTagsBuilder_;

      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public java.util.List<GeneralTagSerializer.GeneralTag> getDocTagsList() {
        if (docTagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(docTags_);
        } else {
          return docTagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public int getDocTagsCount() {
        if (docTagsBuilder_ == null) {
          return docTags_.size();
        } else {
          return docTagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public GeneralTagSerializer.GeneralTag getDocTags(int index) {
        if (docTagsBuilder_ == null) {
          return docTags_.get(index);
        } else {
          return docTagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder setDocTags(
          int index, GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.set(index, value);
          onChanged();
        } else {
          docTagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder setDocTags(
          int index, GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.set(index, builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder addDocTags(GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.add(value);
          onChanged();
        } else {
          docTagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder addDocTags(
          int index, GeneralTagSerializer.GeneralTag value) {
        if (docTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocTagsIsMutable();
          docTags_.add(index, value);
          onChanged();
        } else {
          docTagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder addDocTags(
          GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.add(builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder addDocTags(
          int index, GeneralTagSerializer.GeneralTag.Builder builderForValue) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.add(index, builderForValue.build());
          onChanged();
        } else {
          docTagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder addAllDocTags(
          Iterable<? extends GeneralTagSerializer.GeneralTag> values) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, docTags_);
          onChanged();
        } else {
          docTagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder clearDocTags() {
        if (docTagsBuilder_ == null) {
          docTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          docTagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public Builder removeDocTags(int index) {
        if (docTagsBuilder_ == null) {
          ensureDocTagsIsMutable();
          docTags_.remove(index);
          onChanged();
        } else {
          docTagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder getDocTagsBuilder(
          int index) {
        return getDocTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public GeneralTagSerializer.GeneralTagOrBuilder getDocTagsOrBuilder(
          int index) {
        if (docTagsBuilder_ == null) {
          return docTags_.get(index);  } else {
          return docTagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public java.util.List<? extends GeneralTagSerializer.GeneralTagOrBuilder> 
           getDocTagsOrBuilderList() {
        if (docTagsBuilder_ != null) {
          return docTagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(docTags_);
        }
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder addDocTagsBuilder() {
        return getDocTagsFieldBuilder().addBuilder(
            GeneralTagSerializer.GeneralTag.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public GeneralTagSerializer.GeneralTag.Builder addDocTagsBuilder(
          int index) {
        return getDocTagsFieldBuilder().addBuilder(
            index, GeneralTagSerializer.GeneralTag.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralTag docTags = 5;</code>
       */
      public java.util.List<GeneralTagSerializer.GeneralTag.Builder> 
           getDocTagsBuilderList() {
        return getDocTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder> 
          getDocTagsFieldBuilder() {
        if (docTagsBuilder_ == null) {
          docTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GeneralTagSerializer.GeneralTag, GeneralTagSerializer.GeneralTag.Builder, GeneralTagSerializer.GeneralTagOrBuilder>(
                  docTags_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          docTags_ = null;
        }
        return docTagsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FieldMark)
    }

    // @@protoc_insertion_point(class_scope:FieldMark)
    private static final FieldMark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FieldMark();
    }

    public static FieldMark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FieldMark>
        PARSER = new com.google.protobuf.AbstractParser<FieldMark>() {
      @Override
      public FieldMark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FieldMark(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FieldMark> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FieldMark> getParserForType() {
      return PARSER;
    }

    @Override
    public FieldMark getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldMark_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FieldMark_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017FieldMark.proto\032\020GeneralTag.proto\"d\n\tF" +
      "ieldMark\022\014\n\004type\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004" +
      "desc\030\003 \001(\t\022\017\n\007example\030\004 \001(\t\022\034\n\007docTags\030\005" +
      " \003(\0132\013.GeneralTagB3\n\034io.github.dayeshing.apiface.s" +
      "erializerB\023FieldMarkSerializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GeneralTagSerializer.getDescriptor(),
        });
    internal_static_FieldMark_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FieldMark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FieldMark_descriptor,
        new String[] { "Type", "Name", "Desc", "Example", "DocTags", });
    GeneralTagSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
